name: Update GitHub Stats Cache

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update stats version in README
        run: |
          VERSION=$(date +%s)
          sed -i "s|{{STATS_VERSION}}|$VERSION|g" README.md
          echo "Updated README with version $VERSION"

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update GitHub stats cache busting version"
          git push
